# Use the official Node.js image
FROM node:20-slim

# Set working directory
WORKDIR /app/callsService

# Get shared function remeber thaat the context is at the root of the project not next to this docker file.
COPY shared ../shared

# Copy package.json and package-lock.json
COPY callsService/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY callsService/server.js ./
COPY callsService/controllers ./controllers
COPY callsService/models ./models
COPY callsService/routes ./routes

# Start the app
CMD ["node", "server.js"]
