# Use the official Node.js image
FROM node:20-slim

# Set working directory
WORKDIR /app/cloudinaryService

# Get shared function
COPY shared ../shared

# Copy package.json and package-lock.json
COPY cloudinaryService/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY cloudinaryService/server.js ./
COPY cloudinaryService/middleware ./middleware
COPY cloudinaryService/controllers ./controllers
COPY cloudinaryService/models ./models
COPY cloudinaryService/routes ./routes

# Start the app
CMD ["node", "server.js"]
