# Use the official Node.js image
FROM node:20-slim

# Set working directory
WORKDIR /app/contactsService

# Get shared function
COPY shared ../shared

# Copy package.json and package-lock.json
COPY contactsService/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY contactsService/server.js ./
COPY contactsService/routes ./routes
COPY contactsService/models ./models
COPY contactsService/utils ./utils
COPY contactsService/controllers ./controllers

# Start the app
CMD ["node", "server.js"]
